spring.application.name=resume
server.port=8081

openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration