spring.application.name=resume
spring.datasource.url=jdbc:postgresql://localhost:5432/resume
spring.datasource.username=postgres
spring.datasource.password=1234@asdfK

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
openai.api.key=${OPENAI_API_KEY}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration