spring.application.name=resume
server.port=8081

openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/resume
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true